"""add psychiatrist fields to booking

Revision ID: 05cbd8166583
Revises: 5af5d7981e7b
Create Date: 2026-01-24 21:37:41.044405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cbd8166583'
down_revision = '5af5d7981e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psychiatrist_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('psychiatrist_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.drop_column('payment_ref')
        batch_op.drop_column('amount')
        batch_op.drop_column('psychiatrist_name')
        batch_op.drop_column('psychiatrist_id')

    # ### end Alembic commands ###
