"""fix relationships

Revision ID: 164a2fafae71
Revises: 014aba64c7ca
Create Date: 2026-02-06 14:48:41.772966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164a2fafae71'
down_revision = '014aba64c7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('ml_prob',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('ml_prob',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
