"""whatever you changed

Revision ID: 1764e55e3617
Revises: 6c195a8fdd95
Create Date: 2026-02-13 13:23:15.529583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1764e55e3617'
down_revision = '6c195a8fdd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix2_message_label_message_id'))
        batch_op.create_index(batch_op.f('ix_message_label_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_label_message_id'))
        batch_op.create_index(batch_op.f('ix2_message_label_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###
