"""add trend risk xai fields

Revision ID: 3b78ca9084cc
Revises: d84545fed19e
Create Date: 2026-02-06 12:08:10.783350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b78ca9084cc'
down_revision = 'd84545fed19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- appointment ---
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column(
            'reminded_24h',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('0')
        )
        batch_op.alter_column(
            'reminded_1h',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('0')
        )

    # --- chat_history ---
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vader_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ml_prob', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('explain_tokens', sa.Text(), nullable=True))

        # ✅ keep defaults during SQLite copy
        batch_op.add_column(sa.Column(
            'contains_self_harm', sa.Boolean(), nullable=False, server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'crisis_mode', sa.Boolean(), nullable=False, server_default=sa.text('0')
        ))

        batch_op.alter_column(
            'session_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )
        batch_op.alter_column(
            'sentiment_label',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=20),
            existing_nullable=True
        )

    # --- chat_message ---
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
     batch_op.create_foreign_key(
        "fk_chat_message_session_id_chat_session",
        "chat_session",
        ["session_id"],
        ["id"]
    )


    # --- chat_session ---
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_sentiment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_slope', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_reasons', sa.Text(), nullable=True))

    # --- notification ---
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column(
            'read',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('0')
        )

    # --- psychiatrist_booking ---
    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.alter_column(
            'paid',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=sa.text('0')
        )
        batch_op.create_unique_constraint(
            'uq_user_booking_same_slot',
            ['user_id', 'date', 'time']
        )

    # ✅ Optional cleanup: remove server defaults AFTER batch copy is done
    #op.alter_column('appointment', 'reminded_24h', server_default=None)
    #op.alter_column('appointment', 'reminded_1h', server_default=None)
    #op.alter_column('chat_history', 'contains_self_harm', server_default=None)
    #op.alter_column('chat_history', 'crisis_mode', server_default=None)
    #op.alter_column('notification', 'read', server_default=None)
    #op.alter_column('psychiatrist_booking', 'paid', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_booking_same_slot', type_='unique')
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('risk_reasons')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('trend_label')
        batch_op.drop_column('trend_slope')
        batch_op.drop_column('avg_sentiment')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('sentiment_label',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('crisis_mode')
        batch_op.drop_column('contains_self_harm')
        batch_op.drop_column('explain_tokens')
        batch_op.drop_column('confidence')
        batch_op.drop_column('final_score')
        batch_op.drop_column('ml_prob')
        batch_op.drop_column('vader_score')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('reminded_1h',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('reminded_24h',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
