"""Add is_phi column to User

Revision ID: 5386df5cc906
Revises: 6e5736df57bc
Create Date: 2025-11-05 12:33:18.197774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5386df5cc906'
down_revision = '6e5736df57bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
         op.add_column('user', sa.Column('is_phi', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_phi')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('role', existing_type=sa.String(length=20), nullable=True)

    # ### end Alembic commands ###
