"""Add intent_tag to ChatMessage

Revision ID: 645a21dc36e2
Revises: 1764e55e3617
Create Date: 2026-02-15 18:08:59.288518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645a21dc36e2'
down_revision = '1764e55e3617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent_tag', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('intent_tag')

    # ### end Alembic commands ###
