"""message_label allow multiple labels per message

Revision ID: 6dd0172f163c
Revises: d6381ff0dfe0
Create Date: 2026-02-17 13:49:59.334581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd0172f163c'
down_revision = 'd6381ff0dfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_label', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_message_label_message_id'), type_='unique')
        batch_op.create_unique_constraint('uq_message_label_message_label', ['message_id', 'label'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_label', schema=None) as batch_op:
        batch_op.drop_constraint('uq_message_label_message_label', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_message_label_message_id'), ['message_id'])
        batch_op.alter_column('label',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
