"""add message_label ground truth table

Revision ID: aa78297e50b2
Revises: f90715fd5997
Create Date: 2026-02-06 20:07:55.994565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa78297e50b2'
down_revision = 'f90715fd5997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('labeled_at', sa.DateTime(), nullable=False),
    sa.Column('labeled_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labeled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_label')
    # ### end Alembic commands ###
