"""Add notif_type appointment_dt booking_id to notification

Revision ID: ccfecb9ab986
Revises: 645a21dc36e2
Create Date: 2026-02-16 18:50:28.002984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfecb9ab986'
down_revision = '645a21dc36e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('appointment_dt', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('preferred_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'auto'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('preferred_mode',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'auto'"))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('booking_id')
        batch_op.drop_column('appointment_dt')
        batch_op.drop_column('notif_type')

    # ### end Alembic commands ###
