"""add community tables

Revision ID: d6381ff0dfe0
Revises: ccfecb9ab986
Create Date: 2026-02-17 10:50:49.290082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6381ff0dfe0'
down_revision = 'ccfecb9ab986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_alias', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_anon_alias'), ['anon_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_reports_count'), ['reports_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_user_id'), ['user_id'], unique=False)

    op.create_table('community_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_alias', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comment_anon_alias'), ['anon_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comment_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comment_reports_count'), ['reports_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comment_user_id'), ['user_id'], unique=False)

    op.create_table('community_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'type', name='uq_reaction_post_user_type')
    )
    with op.batch_alter_table('community_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_reaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reaction_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reaction_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reaction_user_id'), ['user_id'], unique=False)

    op.create_table('community_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['community_comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_report_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_report_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_report_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_report_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_report_status'))
        batch_op.drop_index(batch_op.f('ix_community_report_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_report_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_report_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_report_comment_id'))

    op.drop_table('community_report')
    with op.batch_alter_table('community_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_reaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_reaction_type'))
        batch_op.drop_index(batch_op.f('ix_community_reaction_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_reaction_created_at'))

    op.drop_table('community_reaction')
    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_comment_status'))
        batch_op.drop_index(batch_op.f('ix_community_comment_reports_count'))
        batch_op.drop_index(batch_op.f('ix_community_comment_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_comment_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_comment_anon_alias'))

    op.drop_table('community_comment')
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_status'))
        batch_op.drop_index(batch_op.f('ix_community_post_reports_count'))
        batch_op.drop_index(batch_op.f('ix_community_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_post_anon_alias'))

    op.drop_table('community_post')
    # ### end Alembic commands ###
