"""add notification table

Revision ID: d84545fed19e
Revises: aad5a45d4efe
Create Date: 2026-01-27 16:47:58.056301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84545fed19e'
down_revision = 'aad5a45d4efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_chat_history')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chat_session', ['session_id'], ['id'])

    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.alter_column('reminded_24h',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reminded_1h',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychiatrist_booking', schema=None) as batch_op:
        batch_op.alter_column('reminded_1h',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reminded_24h',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_chat_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=10), nullable=True),
    sa.Column('emotion', sa.VARCHAR(length=20), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_history_session_id_chat_session')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###
